name ="anand raj bind"

print(len(name)) # length of the string
print(name.startswith("An")) # check if the string starts with "An"
print(name.endswith("nd")) # check if the string ends with "nd"
print(name.capitalize()) # capitalize the first letter of the string
print(name.upper()) # convert the string to uppercase
print(name.lower()) # convert the string to lowercase

# Escape sequence characters:- Sequence of characters after backslash(\) is called escape sequence characters
# \n is used to print in new line


a = "Aanand \\  is a good boy \n and not a \t \"bad\" boy"
print(a) 